"""
Premium Custom Emoji Registry — Deven Pro
──────────────────────────────────────────
Bot token is generated by a Telegram Premium account,
so bot messages can embed animated premium custom emoji.
Organised into logical packs for easy maintenance.
"""
import re as _re
_ANIMATED = {
    "⚠️": "6098337704682984714",
    "🛑": "6325507973896472524",
    "👋": "6026306335715365949",
    "🤕": "6325636152900453913",
    "❤️": "5287446418909328171",
    "💙": "5285528007342058142",
    "💚": "5287724290408477329",
    "💛": "5287501467505161665",
    "💜": "5287590605256418477",
    "🧡": "5287614480979618146",
    "🖤": "5287447767529055897",
    "🤍": "5287767360340519834",
    "🤎": "5285242409196741959",
    "💕": "5284987172175246592",
    "💖": "5287448931465194557",
    "💗": "5287503091002794719",
    "💘": "5287249000737564644",
    "💔": "5285051678289063571",
    "💓": "5285273758163038115",
    "💎": "6026031174340579961",
    "⭐️": "5285074982781610729",
    "🦋": "5287474383441390368",
    "☹️": "5287450700991720181",
    "🍬": "5287389347383897591",
}
PREMIUM_EMOJI_IDS = {
    "✅": "5444987348334965906", "❌": "5447647474984449520", "🔥": "5116414868357907335",
    "⚡": "5219943216781995020", "💳": "5447453226498552490", "💠": "5870498447068502918",
    "📝": "5444860552310457690", "🌐": "5447602197439218445", "📊": "5445146408153806223",
    "📦": "5303102515301083665", "📋": "5444931419270839381", "⏳": "5258113901106580375",
    "🚀": "4904936030232117798", "⚠️": "4915853119839011973", "💎": "5343636681473935403",
    "👋": "5134476056241112076", "💡": "5301275719681190738", "📈": "5134457377428341766",
    "🔢": "5305652587708572354", "🔌": "5364052602357044385", "⭐": "5343636681473935403",
    "🆓": "5406756500108501710",
    "👑": "5303547611351902889", "🔍": "5258396243666681152",
    "⏱️": "5303243514782443814", "💥": "5122933683820430249", "🆔": "5447311106030726740",
    "👤": "5445174334031166029", "📅": "5116575178012235794", "🔄": "5454245266305604993",
    "🏦": "5303159080020372094", "🥰": "5881784744949062058", "😱": "5868517294618975202",
    "🔷": "5258024802010026053",
    "🔑": "5454386656628991407",
    "📆": "5454074580010295588",
    "👥": "5454371323595744068",
    "🥕": "5116599934203724812",
    "🌳": "5305346287820895195",
    "🦉": "5123344136665039833",
    "🍑": "5258121851091043775",
    "💪": "5305622454218024328",
    "🌝": "5404494035891023578",
    "📁": "5447408120752013199",
    "ℹ️": "5289930378885214069",
    "💀": "5231338559587257737",
    "📢": "5116445341150872576",
    "💰": "5283232570660634549",
    "🔘": "5219901967916084166",
    "🔗": "5447479640547428304",
    "👇": "5305618829265628111",
    "📌": "5447187153274567373",
    "💸": "5447579253723918909",
    "🎉": "5172632227871196306",
    "🎁": "5283031441637148958",
    "🚫": "5116151848855667552",
    "🛒": "5447319442562251569",
    "🔧": "4904936030232117798",
    "⛔️": "5275969776668134187",
    "🥲": "4904468402782864209",
    "☠️": "5231338559587257737",
    "📸": "5445344161333015312",
    "💬": "5447510826304959724",
    "😺": "5118590136149345664",
    "🌍": "5303440357428586778",
    "🔹": "5429436388447655367",
    "📹": "5445158077579952110",
    "📡": "5447448489149625830",
    "📍": "5447187153274567373",
    "🔐": "5258476306152038031",
    "🎯": "5444987348334965906",
    "🤖": "5219943216781995020",
    "🤵": "5445174334031166029",
    "⚡️": "5219943216781995020",
    "⏸️": "5258113901106580375",
    "▶️": "5219943216781995020",
    "✉": "5444860552310457690",
    "✉️": "5444860552310457690",
    "🛰": "5447602197439218445",
    "🛰️": "5447602197439218445",
    "🩺": "5444931419270839381",
    "🎚": "5219943216781995020",
    "🎚️": "5219943216781995020",
    "📐": "5444931419270839381",
    "🏓": "5219943216781995020",
    "🔎": "5258396243666681152",
    "📭": "5444860552310457690",
    "📩": "5444860552310457690",
    "⛔": "5275969776668134187",
    "🔻": "5447647474984449520",
    "🏛": "5303159080020372094",
    "🏪": "5447453226498552490",
    "📖": "5444860552310457690",
    "🗂": "5447408120752013199",
    "🔁": "5454245266305604993",
    "🧭": "5447602197439218445",
}
_CUSTOM_EMOJI_RE = _re.compile(r'<tg-emoji\s+emoji-id="\d+">([^<]*)</tg-emoji>')
_HTML_TAG_RE = _re.compile(r'(<tg-emoji\s+emoji-id="\d+">[^<]*</tg-emoji>|<[^>]+>)', _re.IGNORECASE)
def _ce(eid: str, fallback: str) -> str:
    """Build a custom emoji HTML tag using the precise emoji-id supplied.
    Uses the caller-provided eid directly so every EMOJI key keeps its
    intended animation.  PREMIUM_EMOJI_IDS is reserved for plain-emoji
    conversion in _premiumize_simple and is never mutated here."""
    return f'<tg-emoji emoji-id="{eid}">{fallback}</tg-emoji>'
def strip_custom_emoji(text: str) -> str:
    """Remove Telegram custom emoji tags for fallback paths without plain emoji."""
    return _CUSTOM_EMOJI_RE.sub("", str(text or ""))
def is_emoji_send_error(err_text: str) -> bool:
    """Return True if a Telegram error is caused by premium custom emoji tags."""
    err = str(err_text or "").lower()
    return any(p in err for p in (
        "document_invalid",
        "document invalid",
        "wrong custom emoji",
        "custom emoji identifier",
        "invalid custom emoji",
    ))
_TOKEN_RE = _re.compile(r'(<[^>]+>|&[a-zA-Z][a-zA-Z0-9]*;|&#\d+;)')
def boldify_b_tags(text: str) -> str:
    """Render <b>/<strong> content as Unicode sans-serif bold, then drop the
    tags. Content inside <code>/<pre> is never bolded (stays tap-to-copy) and
    HTML entities (&amp; etc.) are preserved intact."""
    text = str(text or "")
    if "<b>" not in text and "<strong>" not in text:
        return text
    out = []
    skip_depth = 0
    b_depth = 0
    pos = 0
    for m in _TOKEN_RE.finditer(text):
        if m.start() > pos:
            chunk = text[pos:m.start()]
            out.append(bold(chunk) if (b_depth and not skip_depth) else chunk)
        tok = m.group(0)
        low = tok.lower()
        if low in ("<b>", "<strong>"):
            b_depth += 1
        elif low in ("</b>", "</strong>"):
            b_depth = max(0, b_depth - 1)
        elif low.startswith("<code") or low.startswith("<pre"):
            skip_depth += 1
            out.append(tok)
        elif low.startswith("</code") or low.startswith("</pre"):
            skip_depth = max(0, skip_depth - 1)
            out.append(tok)
        else:
            out.append(tok)
        pos = m.end()
    if pos < len(text):
        chunk = text[pos:]
        out.append(bold(chunk) if (b_depth and not skip_depth) else chunk)
    return "".join(out)
def _premiumize_simple(text: str) -> str:
    """Replace plain emoji with premium <tg-emoji> tags using placeholder approach."""
    if not text:
        return text
    placeholders = []
    result = text
    for i, (emoji, doc_id) in enumerate(sorted(PREMIUM_EMOJI_IDS.items(), key=lambda item: len(item[0]), reverse=True)):
        placeholder = f"\x00PE{i:02d}\x00"
        placeholders.append((placeholder, doc_id, emoji))
        result = result.replace(emoji, placeholder)
    for placeholder, doc_id, emoji in placeholders:
        result = result.replace(placeholder, f'<tg-emoji emoji-id="{doc_id}">{emoji}</tg-emoji>')
    return result
def premiumize_emoji_html(text: str) -> str:
    """Convert plain emoji in HTML bot text to Telegram premium custom emoji tags.
    Uses simple placeholder replacement (like commands/bot.py).
    Existing <tg-emoji> tags and <code>/<pre> content are left untouched so card
    lines, IDs, and debug blobs stay copy-friendly.
    """
    text = str(text or "")
    if not text:
        return text
    out: list[str] = []
    skip_depth = 0
    pos = 0
    for match in _HTML_TAG_RE.finditer(text):
        if match.start() > pos:
            chunk = text[pos:match.start()]
            if skip_depth:
                out.append(chunk)
            else:
                out.append(_premiumize_simple(chunk))
        tag = match.group(0)
        out.append(tag)
        tag_lower = tag.lower()
        if tag_lower.startswith("<code") or tag_lower.startswith("<pre"):
            skip_depth += 1
        elif tag_lower.startswith("</code") or tag_lower.startswith("</pre"):
            skip_depth = max(0, skip_depth - 1)
        pos = match.end()
    if pos < len(text):
        chunk = text[pos:]
        if skip_depth:
            out.append(chunk)
        else:
            out.append(_premiumize_simple(chunk))
    return "".join(out)
EMOJI = {
    "activity": _ce("5454245266305604993", "🔄"),
    "admin": _ce("5472308992514464048", "🛡"),
    "alarm": _ce("5852753450382659113", "🚨"),
    "alert": _ce("4915853119839011973", "⚠️"),
    "angel": _ce("5438577831200178997", "🧿"),
    "angry": _ce("6136392768487954831", "😠"),
    "antenna": _ce("6097926401434851083", "📶"),
    "approved": _ce("5444987348334965906", "✅"),
    "apprv": _ce("5444987348334965906", "✅"),
    "arrow_curve": _ce("5253997076169115797", "↪️"),
    "arrow_left": _ce("5253997076169115797", "⬅️"),
    "arrow_right": _ce("5253997076169115797", "➡️"),
    "arrow_up": _ce("6098076497656944429", "⚡️"),
    "badge": _ce("6100448805663020296", "📛"),
    "bag": _ce("6136159783692017451", "⟐"),
    "bank": _ce("5472308992514464048", "🏦"),
    "bank_raw": _ce("6098365012085053396", "🏦"),
    "bat1": _ce("6138798143447244059", "🦇"),
    "bat2": _ce("6136246765369694911", "🦇"),
    "bat3": _ce("6138944241054783305", "🦇"),
    "bat4": _ce("6138477872030947849", "🦇"),
    "bat5": _ce("6136363339372043522", "🦇"),
    "bell": _ce("5116445341150872576", "📢"),
    "bin": _ce("5472250091332993630", "🗃"),
    "black_dot": _ce("5316858509571144216", "⚫"),
    "blue_dot": _ce("5472308992514464048", "🔵"),
    "boom": _ce("6147565374289220368", "💥"),
    "braintree": _ce("5472250091332993630", "🌳"),
    "bronze": _ce("6100586674113222901", "🥉"),
    "bulb": _ce("6098387861311068868", "💡"),
    "calendar": _ce("5116575178012235794", "📅"),
    "calendar_raw": _ce("5082628525303792441", "📅"),
    "cart": _ce("5472250091332993630", "🛒"),
    "cat1": _ce("6136480866857130917", "🐱"),
    "cat2": _ce("6138551474885499690", "🐱"),
    "champion": _ce("5467406098367521267", "🏆"),
    "chart": _ce("5445146408153806223", "📊"),
    "chart_down": _ce("6098257904190624738", "📉"),
    "chart_up": _ce("6098257904190624738", "📈"),
    "chart_up_raw": _ce("6098163741327629439", "📈"),
    "chat": _ce("6100672624998750369", "💬"),
    "check": _ce("5444987348334965906", "✅"),
    "check2": _ce("6253414379442670769", "✅"),
    "check3": _ce("6253754970349243649", "✅"),
    "checkmark": _ce("5444987348334965906", "✅"),
    "checkout": _ce("5472250091332993630", "🛒"),
    "clipboard": _ce("5444931419270839381", "📋"),
    "clock": _ce("5303243514782443814", "⏱️"),
    "code": _ce("6098076497656944429", "🖋"),
    "coin": _ce("6100448805663020296", "🪙"),
    "collapse": _ce("6097926401434851083", "🔼"),
    "comet": _ce("6100586674113222901", "🔥"),
    "confetti": _ce("5424818078833715060", "📣"),
    "cop": _ce("5472308992514464048", "👮"),
    "copy": _ce("6100672624998750369", "📋"),
    "cross": _ce("5447647474984449520", "❌"),
    "crown_raw": _ce("5319149831673887746", "👑"),
    "crystal": _ce("6100448805663020296", "🔮"),
    "cycle": _ce("5454245266305604993", "🔄"),
    "database": _ce("5316858509571144216", "🗄"),
    "dead": _ce("5447647474984449520", "❌"),
    "decl": _ce("5447647474984449520", "❌"),
    "diamond": _ce("5343636681473935403", "💎"),
    "dice": _ce("5436113877181941026", "🎲"),
    "dizzy": _ce("6136389654636665179", "⟐"),
    "dollar": _ce("5472250091332993630", "💵"),
    "downgrade": _ce("5852753450382659113", "⬇️"),
    "elite": _ce(_ANIMATED.get("💎", "6100448805663020296"), "💎"),
    "expand": _ce("6097926401434851083", "🔽"),
    "export": _ce("5424818078833715060", "📤"),
    "eye": _ce("5188217332748527444", "👁"),
    "file": _ce("6100672624998750369", "📄"),
    "filter": _ce("5188217332748527444", "🔬"),
    "fingerprint": _ce("5316858509571144216", "🔏"),
    "fire": _ce("6100586674113222901", "🔥"),
    "firewall": _ce("5472308992514464048", "🧱"),
    "flag": _ce("6097926401434851083", "🚩"),
    "flag1": _ce("6136165822416033423", "⟐"),
    "flag2": _ce("6136330925253860126", "⟐"),
    "flame": _ce("6100586674113222901", "🔥"),
    "fleur": _ce("6136165822416033423", "⟐"),
    "folder": _ce("6100672624998750369", "📁"),
    "forward": _ce("5253997076169115797", "▶️"),
    "gear": _ce("4904936030232117798", "🔧"),
    "gem": _ce("5343636681473935403", "💎"),
    "generate": _ce("5305652587708572354", "🔢"),
    "ghost": _ce("5240241223632954241", "👻"),
    "gift": _ce("5283031441637148958", "🎁"),
    "globe": _ce("5447602197439218445", "🌐"),
    "glow": _ce("6136204644625423818", "⚡"),
    "gold": _ce("5467406098367521267", "🥇"),
    "graph": _ce("6098257904190624738", "📊"),
    "green_dot": _ce("6100395724162210221", "🟢"),
    "hammer": _ce("6098076497656944429", "🔨"),
    "hand": _ce("6136205108481890460", "⟐"),
    "handshake": _ce("6136198451282581752", "⟐"),
    "hash": _ce("5305652587708572354", "🔢"),
    "heart": _ce("5881784744949062058", "🥰"),
    "heart2": _ce("6136585445015821278", "❤️"),
    "heart3": _ce("6136470835319351236", "❤️"),
    "heart_blue": _ce(_ANIMATED.get("💙", "5285528007342058142"), "💙"),
    "heart_fire": _ce("6100586674113222901", "❤️‍🔥"),
    "heart_gold": _ce(_ANIMATED.get("💛", "5287501467505161665"), "💛"),
    "heart_purple": _ce(_ANIMATED.get("💜", "5287590605256418477"), "💜"),
    "home": _ce("6100448805663020296", "🏠"),
    "hourglass": _ce("5258113901106580375", "⏳"),
    "hundred": _ce("6100395724162210221", "💯"),
    "id": _ce("5197593250650680436", "🆔"),
    "id_card": _ce("5447311106030726740", "🆔"),
    "import_data": _ce("6100672624998750369", "📥"),
    "inbox": _ce("6100672624998750369", "📥"),
    "info": _ce("5289930378885214069", "ℹ️"),
    "invoice": _ce("6100672624998750369", "🧾"),
    "joystick": _ce("6098076497656944429", "🕹"),
    "key": _ce("5316858509571144216", "🔑"),
    "laptop": _ce("6136618494789163433", "💻"),
    "laugh": _ce("6138950679210760878", "⟐"),
    "leaf": _ce("6136525109315245846", "⟐"),
    "legend": _ce("5467406098367521267", "⚜️"),
    "lightning": _ce("6098076497656944429", "🌩"),
    "load": _ce("5303382628773161521", "📂"),
    "love": _ce("6138851255012826209", "❤️"),
    "love2": _ce("6138851255012826209", "❤️"),
    "love_face": _ce("6100144816467744473", "🥰"),
    "magic": _ce("6100586674113222901", "🔥"),
    "mail": _ce("6100672624998750369", "📧"),
    "medal": _ce("5467406098367521267", "🏅"),
    "megaphone": _ce("5116445341150872576", "📢"),
    "meter": _ce("6098076497656944429", "📏"),
    "midnight": _ce("5316858509571144216", "🌙"),
    "money": _ce("6136204644625423818", "💰"),
    "mute": _ce("5240241223632954241", "🔕"),
    "network": _ce("6097926401434851083", "🕸"),
    "neutral": _ce("6253319739838303271", "⟐"),
    "news": _ce("6136389654636665179", "⟐"),
    "newuser": _ce("6026306335715365949", "🆕"),
    "numbers": _ce("6098132224857610496", "🔢"),
    "orange_dot": _ce("6100586674113222901", "🟠"),
    "outbox": _ce("5424818078833715060", "📤"),
    "owner": _ce("5303547611351902889", "👑"),
    "party": _ce("5172632227871196306", "🎉"),
    "pass_card": _ce("5472250091332993630", "🎟"),
    "paste": _ce("6100672624998750369", "📎"),
    "pause": _ce("5303382628773161521", "⏸"),
    "payment": _ce("5472250091332993630", "💲"),
    "paypal": _ce("5472250091332993630", "🅿️"),
    "pending": _ce("5258113901106580375", "⏳"),
    "pin": _ce("6100395724162210221", "📌"),
    "play": _ce("6098076497656944429", "▶️"),
    "premium": _ce("5343636681473935403", "💎"),
    "premium_alert": _ce("4915853119839011973", "⚠️"),
    "premium_badge": _ce("5343636681473935403", "💎"),
    "premium_doc": _ce("6100672624998750369", "✍️"),
    "premium_fast": _ce("6098076497656944429", "⚡️"),
    "premium_hot": _ce("5116414868357907335", "🔥"),
    "premium_lock": _ce("5472308992514464048", "🔐"),
    "premium_ok": _ce("5444987348334965906", "✅"),
    "premium_stop": _ce("5275969776668134187", "⛔️"),
    "premium_wave": _ce(_ANIMATED["👋"], "👋"),
    "pro_badge": _ce("5467406098367521267", "👑"),
    "processing": _ce("5258113901106580375", "⏳"),
    "proxy": _ce("6097926401434851083", "🌐"),
    "pulse": _ce(_ANIMATED.get("💓", "6098076497656944429"), "💓"),
    "purple_dot": _ce("6100448805663020296", "🟣"),
    "pushpin": _ce("6100395724162210221", "📍"),
    "rainbow": _ce("6100448805663020296", "🌈"),
    "random": _ce("5436113877181941026", "🎲"),
    "receipt": _ce("6100672624998750369", "🧾"),
    "red_dot": _ce("5852753450382659113", "🔴"),
    "refresh": _ce("5454245266305604993", "🔄"),
    "refund": _ce("5253997076169115797", "↩️"),
    "reply": _ce("5253997076169115797", "↩️"),
    "ribbon": _ce("6100448805663020296", "🎗"),
    "rising": _ce("6098257904190624738", "📈"),
    "robot": _ce("6098076497656944429", "🤖"),
    "rocket": _ce("6098076497656944429", "⚡️"),
    "salute": _ce("6136205108481890460", "⟐"),
    "satellite": _ce("6097926401434851083", "📡"),
    "save": _ce("6100395724162210221", "💾"),
    "scream": _ce("6097986153019873224", "😱"),
    "search_raw": _ce("5467639224897390419", "🔍"),
    "server": _ce("5316858509571144216", "🖥"),
    "shield": _ce("5472308992514464048", "🛡"),
    "silver": _ce("5472308992514464048", "🥈"),
    "siren": _ce("5852753450382659113", "🚨"),
    "skip": _ce("5253997076169115797", "⏭"),
    "skull": _ce("6325636152900453913", "💀"),
    "slow": _ce("5303382628773161521", "🐌"),
    "smirk": _ce("5438330913530333277", "⟐"),
    "snowflake": _ce("5472308992514464048", "❄️"),
    "sparkle": _ce("6100586674113222901", "🔥"),
    "sparkle1": _ce("6136525109315245846", "⟐"),
    "sparkle2": _ce("6253754970349243649", "✨"),
    "sparkle3": _ce("6255501076418530072", "✨"),
    "speed": _ce("6098076497656944429", "💨"),
    "spy": _ce("5188217332748527444", "🕵️"),
    "star": _ce("5429436388447655367", "🔹"),
    "star1": _ce("6136330925253860126", "✨"),
    "star2": _ce("6136275172283391020", "✨"),
    "star3": _ce("6136272350489877760", "✨"),
    "star4": _ce("6136618494789163433", "✨"),
    "star5": _ce("6255511886851214223", "✨"),
    "star_raw": _ce("6026106482297147601", "⭐"),
    "stop_btn": _ce(_ANIMATED["🛑"], "⏹"),
    "stopwatch": _ce("5303243514782443814", "⏱️"),
    "stopwatch_raw": _ce("5787488119490088755", "⏱️"),
    "stripe": _ce("6098076497656944429", "💳"),
    "subscription": _ce("5454245266305604993", "🔄"),
    "success": _ce("5444987348334965906", "✅"),
    "sunrise": _ce("6100586674113222901", "🌅"),
    "support": _ce("6100672624998750369", "🆘"),
    "tag": _ce("5418010521309815154", "🏷"),
    "target": _ce("6100395724162210221", "🎯"),
    "terminal": _ce("6098076497656944429", "💻"),
    "timeout": _ce("5413704112220949842", "⏱"),
    "timer": _ce("5303243514782443814", "⏱️"),
    "toolbox": _ce("6098076497656944429", "🧰"),
    "top": _ce("5467406098367521267", "🔝"),
    "tornado": _ce("6098076497656944429", "🌪"),
    "trophy": _ce("5303547611351902889", "👑"),
    "tunnel": _ce("6097926401434851083", "🚇"),
    "unknown": _ce("5436113877181941026", "❔"),
    "unlock": _ce("5444987348334965906", "✅"),
    "unverified": _ce("5447647474984449520", "❌"),
    "upgrade": _ce("6098076497656944429", "⚡️"),
    "user": _ce("5445174334031166029", "👤"),
    "user_raw": _ce("5258011929993026890", "👤"),
    "verified": _ce("5444987348334965906", "✅"),
    "vip": _ce("5343636681473935403", "💎"),
    "vpn": _ce("5316858509571144216", "🔐"),
    "wallet": _ce("5283232570660634549", "💰"),
    "warning": _ce("4915853119839011973", "⚠️"),
    "wave": _ce("6097926401434851083", "🌊"),
    "white_dot": _ce("6100395724162210221", "✅"),
    "wink": _ce("6136672117455853855", "⟐"),
    "wrench": _ce("6098076497656944429", "🔧"),
    "yellow_dot": _ce("5895443668663275064", "🟡"),
    "zap": _ce("6098076497656944429", "⚡"),
    "3ds": '<tg-emoji emoji-id="6285068812400202707">🔐</tg-emoji>',
    "arrow_down": '<tg-emoji emoji-id="6084743519010820583">👇</tg-emoji>',
    "back": '<tg-emoji emoji-id="5253997076169115797">🔙</tg-emoji>',
    "ban": '<tg-emoji emoji-id="5116151848855667552">🤕</tg-emoji>',
    "blocked": '<tg-emoji emoji-id="5116151848855667552">🚫</tg-emoji>',
    "bolt": '<tg-emoji emoji-id="5219943216781995020">⚡️</tg-emoji>',
    "broadcast": '<tg-emoji emoji-id="5474263443152316384">📣</tg-emoji>',
    "card": '<tg-emoji emoji-id="6267128480601741166">💳</tg-emoji>',
    "charged": '<tg-emoji emoji-id="5123163417326126159">✅</tg-emoji>',
    "crown": '<tg-emoji emoji-id="6266995104687330978">👑</tg-emoji>',
    "danger": '<tg-emoji emoji-id="5852753450382659113">🔴</tg-emoji>',
    "declined": '<tg-emoji emoji-id="5121063440311386962">❌</tg-emoji>',
    "error": '<tg-emoji emoji-id="5447644880824181073">⚠️</tg-emoji>',
    "expired": '<tg-emoji emoji-id="6266866272848321043">⏰</tg-emoji>',
    "free": '<tg-emoji emoji-id="5406756500108501710">🆓</tg-emoji>',
    "hitting": '<tg-emoji emoji-id="5454415424319931791">⌛️</tg-emoji>',
    "infinity": '<tg-emoji emoji-id="5116512467194741904">♾</tg-emoji>',
    "join": '<tg-emoji emoji-id="4916086774649848789">8️⃣</tg-emoji>',
    "link": '<tg-emoji emoji-id="6267115986541877538">🔗</tg-emoji>',
    "live": '<tg-emoji emoji-id="5219672809936006424">🔥</tg-emoji>',
    "lock": '<tg-emoji emoji-id="6282846669335702032">🔒</tg-emoji>',
    "num_1": '<tg-emoji emoji-id="5404500925018564494">👨🏻‍💻</tg-emoji>',
    "num_2": '<tg-emoji emoji-id="4904936030232117798">🍀</tg-emoji>',
    "num_3": '<tg-emoji emoji-id="5134377151734219769">🍑</tg-emoji>',
    "num_4": '<tg-emoji emoji-id="5305726937887433606">🍆</tg-emoji>',
    "num_5": '<tg-emoji emoji-id="5283282345036646926">♥️</tg-emoji>',
    "num_6": '<tg-emoji emoji-id="5139005588881015916">6️⃣</tg-emoji>',
    "num_7": '<tg-emoji emoji-id="5309887343858060393">👾</tg-emoji>',
    "plan": '<tg-emoji emoji-id="5197269100878907942">✍️</tg-emoji>',
    "plug": '<tg-emoji emoji-id="4904742417401381633">🦏</tg-emoji>',
    "question": '<tg-emoji emoji-id="5436113877181941026">❓</tg-emoji>',
    "regenerate": '<tg-emoji emoji-id="6066348702363031988">🔄</tg-emoji>',
    "risky": '<tg-emoji emoji-id="5895443668663275064">🟡</tg-emoji>',
    "scr": '<tg-emoji emoji-id="5134457377428341766">9️⃣</tg-emoji>',
    "search": '<tg-emoji emoji-id="5258274739041883702">🔍</tg-emoji>',
    "stats": '<tg-emoji emoji-id="5231200819986047254">📊</tg-emoji>',
    "stopped": '<tg-emoji emoji-id="6325507973896472524">🛑</tg-emoji>',
    "ticket": '<tg-emoji emoji-id="5418010521309815154">🎫</tg-emoji>',
    "trash": '<tg-emoji emoji-id="5445267414562389170">🗑</tg-emoji>',
    "users": '<tg-emoji emoji-id="5134155514241876731">👥</tg-emoji>',
    "welcome": '<tg-emoji emoji-id="5258079378159453410">👋</tg-emoji>',
}
_BOLD_UPPER = 0x1D5D4
_BOLD_LOWER = 0x1D5EE
_BOLD_DIGIT = 0x1D7EC
def bold(text) -> str:
    """Convert ASCII letters/digits to Unicode sans-serif bold (𝗯𝗼𝗹𝗱).
    Non-ASCII (emoji, accents, symbols) passes through untouched. Apply this
    BEFORE html.escape so escape-generated entities (&amp;) are never bolded.
    Do NOT use inside <code> — bold glyphs break tap-to-copy."""
    out = []
    for ch in str(text or ""):
        o = ord(ch)
        if 0x41 <= o <= 0x5A:
            out.append(chr(_BOLD_UPPER + o - 0x41))
        elif 0x61 <= o <= 0x7A:
            out.append(chr(_BOLD_LOWER + o - 0x61))
        elif 0x30 <= o <= 0x39:
            out.append(chr(_BOLD_DIGIT + o - 0x30))
        else:
            out.append(ch)
    return "".join(out)
import html as _html
DIV = "━━━━━━━━━━━━━━━━━"
def bv(value) -> str:
    """A display value in unicode bold, html-escaped (bold first so escape
    entities like &amp; are never bolded)."""
    return _html.escape(bold(str(value)))
def row(label, value, copy=False) -> str:
    """One ▸ row. Label plain, value bold — unless copy=True, where the value
    goes in <code> to stay tap-to-copy (cards, IDs)."""
    if copy:
        return f"▸ {label} · <code>{_html.escape(str(value))}</code>"
    return f"▸ {label} · {bv(value)}"
_MONO = {
    "success": _ce("5444987348334965906", "✅"), "charged": _ce("5444987348334965906", "✅"),
    "approved": _ce("5444987348334965906", "✅"), "checkmark": _ce("5444987348334965906", "✅"),
    "verified": _ce("5444987348334965906", "✅"), "premium_ok": _ce("5444987348334965906", "✅"),
    "check": _ce("5444987348334965906", "✅"), "live": _ce("5444987348334965906", "✅"),
    "unlock": _ce("5444987348334965906", "✅"), "apprv": _ce("5444987348334965906", "✅"),
    "declined": _ce("5447647474984449520", "❌"), "dead": _ce("5447647474984449520", "❌"),
    "danger": _ce("5447647474984449520", "❌"), "ban": _ce("5447647474984449520", "❌"),
    "cross": _ce("5447647474984449520", "❌"), "blocked": _ce("5447647474984449520", "❌"),
    "unverified": _ce("5447647474984449520", "❌"), "decl": _ce("5447647474984449520", "❌"),
    "stopped": _ce("5275969776668134187", "⛔️"), "premium_stop": _ce("5275969776668134187", "⛔️"),
    "warning": _ce("4915853119839011973", "⚠️"), "error": _ce("4915853119839011973", "⚠️"),
    "alert": _ce("4915853119839011973", "⚠️"), "premium_alert": _ce("4915853119839011973", "⚠️"),
    "risky": _ce("4915853119839011973", "⚠️"),
    "info": _ce("5289930378885214069", "ℹ️"), "question": _ce("5289930378885214069", "ℹ️"),
    "premium_badge": _ce("5343636681473935403", "💎"), "diamond": _ce("5343636681473935403", "💎"),
    "gem": _ce("5343636681473935403", "💎"), "premium": _ce("5343636681473935403", "💎"),
    "vip": _ce("5343636681473935403", "💎"), "premium_hot": _ce("5116414868357907335", "🔥"),
    "crown": _ce("5303547611351902889", "👑"), "owner": _ce("5303547611351902889", "👑"),
    "star": _ce("5429436388447655367", "🔹"), "trophy": _ce("5303547611351902889", "👑"),
    "refresh": _ce("5454245266305604993", "🔄"), "regenerate": _ce("5454245266305604993", "🔄"),
    "cycle": _ce("5454245266305604993", "🔄"), "timer": _ce("5303243514782443814", "⏱️"),
    "stopwatch": _ce("5303243514782443814", "⏱️"), "clock": _ce("5303243514782443814", "⏱️"),
    "hourglass": _ce("5258113901106580375", "⏳"), "pending": _ce("5258113901106580375", "⏳"),
    "hitting": _ce("5258113901106580375", "⏳"), "processing": _ce("5258113901106580375", "⏳"),
    "lock": _ce("5258476306152038031", "🔐"),
    "activity": _ce("5454245266305604993", "🔄"), "bolt": _ce("5219943216781995020", "⚡"),
    "calendar": _ce("5116575178012235794", "📅"), "chart": _ce("5445146408153806223", "📊"),
    "stats": _ce("5445146408153806223", "📊"), "clipboard": _ce("5444931419270839381", "📋"),
    "gear": _ce("4904936030232117798", "🔧"), "generate": _ce("5305652587708572354", "🔢"),
    "gift": _ce("5283031441637148958", "🎁"), "globe": _ce("5447602197439218445", "🌐"),
    "hash": _ce("5305652587708572354", "🔢"), "heart": _ce("5881784744949062058", "🥰"),
    "id_card": _ce("5447311106030726740", "🆔"), "link": _ce("5447479640547428304", "🔗"),
    "bell": _ce("5116445341150872576", "📢"), "megaphone": _ce("5116445341150872576", "📢"),
    "party": _ce("5172632227871196306", "🎉"),
    "plan": _ce("5444860552310457690", "📝"), "ticket": _ce("5283031441637148958", "🎁"),
    "user": _ce("5445174334031166029", "👤"), "users": _ce("5454371323595744068", "👥"),
    "wallet": _ce("5283232570660634549", "💰"),
}
def e(key: str) -> str:
    """Render an in-text icon as a premium custom emoji (old.py black pack).
    Decorative keys return nothing, keeping responses minimal. Buttons are
    unaffected (they read the EMOJI map via emoji_id())."""
    return _MONO.get(key, "")
def plain_emoji(key: str) -> str:
    """Render a named emoji as plain text for button labels and alerts."""
    value = EMOJI.get(key, "✨")
    match = _CUSTOM_EMOJI_RE.fullmatch(value)
    if match:
        return match.group(1)
    return _CUSTOM_EMOJI_RE.sub(r"\1", value)
def emoji_id(key: str):
    """Extract the custom emoji document ID for Telegram button icons."""
    value = EMOJI.get(key, "")
    match = _re.search(r'emoji-id="(\d+)"', value)
    return int(match.group(1)) if match else None
PREMIUM_LINE_ICONS = (
    "premium_badge",
    "premium_fast",
    "premium_hot",
    "premium_ok",
    "premium_doc",
    "premium_lock",
    "premium_wave",
)
def premium_icon(index: int = 0) -> str:
    """Return a rotating validated premium emoji for line decoration."""
    return EMOJI[PREMIUM_LINE_ICONS[index % len(PREMIUM_LINE_ICONS)]]
def premium_line(text: str, index: int = 0, indent: str = "  ") -> str:
    """Prefix one visible line with a premium emoji."""
    return f"{indent}{premium_icon(index)} {text}"
def premiumize_lines(text: str, start: int = 0) -> str:
    """Prefix non-empty, non-divider lines with rotating premium emoji."""
    out = []
    idx = start
    for raw in str(text or "").splitlines():
        stripped = raw.strip()
        if not stripped or set(stripped) <= {"─", "━", "-", "—"}:
            out.append(raw)
            continue
        out.append(premium_line(stripped, idx, indent=""))
        idx += 1
    return "\n".join(out)